USE  DBQUIZ


CREATE TABLE TBL_ADMIN
(
AD_ID INT IDENTITY PRIMARY KEY,
AD_NAME NVARCHAR(20) NOT NULL UNIQUE,
AD_PASSWORD NVARCHAR(20) NOT NULL
)

CREATE TABLE TBL_QUESTIONS
(
QUESTION_ID INT IDENTITY PRIMARY KEY,
Q_TEXT NVARCHAR(MAX) NOT NULL,
OPA NVARCHAR(20) NOT NULL UNIQUE,
OPB NVARCHAR(20) NOT NULL UNIQUE,
OPC NVARCHAR(20) NOT NULL UNIQUE,
OPD NVARCHAR(20) NOT NULL UNIQUE,
COP NVARCHAR(20) NOT NULL

)

CREATE TABLE TBL_STUDENT
(

S_ID INT IDENTITY PRIMARY KEY,
S_NAME NVARCHAR(20) NOT NULL UNIQUE,
S_PASSWORD NVARCHAR(20) NOT NULL,
S_IMAGE NVARCHAR(MAX) NOT NULL
)

CREATE TABLE TBL_SETEXAM
(
EXAM_ID INT IDENTITY PRIMARY KEY,
EXAM_DATE DATETIME,
EXAM_FK_STU INT FOREIGN KEY REFERENCES TBL_STUDENT (S_ID),
EXAM_NAME NVARCHAR(50) NOT NULL,
EXAM_STD_SCORE INT
)







