//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_STUDENT
    {
        public TBL_STUDENT()
        {
            this.TBL_SETEXAM = new HashSet<TBL_SETEXAM>();
        }
    
        public int S_ID { get; set; }
        public string S_NAME { get; set; }
        public string S_PASSWORD { get; set; }
        public string S_IMAGE { get; set; }
    
        public virtual ICollection<TBL_SETEXAM> TBL_SETEXAM { get; set; }
    }
}
